remote_theme: just-the-docs/just-the-docs@v0.9.0

plugins:
  - jekyll-seo-tag

title: "XIV JP Raids"
description: "Final Fantasy XIV Raid Macros for JP"

favicon_ico: "favicon.ico"

color_scheme: dark

aux_links:
  "Elemental DC Raid Macros Discord":
    - "https://discord.gg/WEzhVHwAU6"
  "Elemental Raiding Discord":
    - "https://discord.gg/BveSrCYwMS"
  "Github":
    - "https://github.com/xivjpraids/xivjpraids"

aux_links_new_tab: true

enable_copy_code_button: true

back_to_top: true
back_to_top_text: "Back to top"

collections:
  current:
    permalink: "/:collection/:path/"
    output: true
  raids:
    permalink: "/:collection/:path/"
    output: true
  ultimates:
    permalink: "/:collection/:path/"
    output: true

# The order and names here determines the order in the sidebar
just_the_docs:
  collections:
    current:
      name: 7.4 Into the Mist
    raids:
      name: Archives
